In [ ]:
a=[8,5,3,9,1]
a.sort()
print(a)

[1, 3, 5, 8, 9]


In [ ]:
a = [8,5,3,9,1]
b = sorted(a)
print(b)
print(a)

[1, 3, 5, 8, 9]
[8, 5, 3, 9, 1]


In [16]:
import numpy as np

In [18]:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.linspace(1,12,6)
print(a)

[ 1.   3.2  5.4  7.6  9.8 12. ]


In [ ]:
#divided in linspace and reshaping
a=np.linspace(1,13,10).reshape(2,5)
print(a)

[[ 1.          2.33333333  3.66666667  5.          6.33333333]
 [ 7.66666667  9.         10.33333333 11.66666667 13.        ]]


In [20]:
#reshaping
a=np.array([45,67,89,2,34,98,5,1]).reshape(2,4)
print(a)

[[45 67 89  2]
 [34 98  5  1]]


In [22]:
#resize changes the shape of original array
#reshape changes needs saving in another variable
a=np.array([45,1,5,7,22,5,1,7])
a.resize(2,4)
print(a)
b=np.array([45,1,5,7,22,5,1,7])
b.reshape(2,4)
print(b)
c=np.array([45,1,5,7,22,5,1,7])
e=b.reshape(2,4)
print(e)

[[45  1  5  7]
 [22  5  1  7]]
[45  1  5  7 22  5  1  7]
[[45  1  5  7]
 [22  5  1  7]]


In [ ]:
#sub
a=np.array([45,1,5,7,22,5,1,7])
b=np.array([2,1,2,4,2,20,2,1])
print(a-b)

[ 43   0   3   3  20 -15  -1   6]


In [ ]:
#add
a=np.array([45,1,5,7,22,5,1,7])
b=np.array([2,1,2,4,2,20,2,1])
print(a+b)

[47  2  7 11 24 25  3  8]


In [ ]:
#sort,min,max
a=np.array([45,1,5,7,22,5,1,7])
print(a.min())
print(a.max())

1
45
None


In [ ]:
#multi
a=np.array([45,1,5,7,22,5,1,7]).reshape(2,4)
b=np.array([2,1,2,4,2,20,2,1]).reshape(2,4)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
c=a*b
print(c)

[[45  1  5  7]
 [22  5  1  7]]
-----------------------
[[ 2  1  2  4]
 [ 2 20  2  1]]
-----------------------
[[ 90   1  10  28]
 [ 44 100   2   7]]


In [24]:
#one to one mul
a=np.array([45,1,5,7]).reshape(2,2)
b=np.array([2,1,2,4]).reshape(2,2)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
print(a@b)

[[45  1]
 [ 5  7]]
-----------------------
[[2 1]
 [2 4]]
-----------------------
[[92 49]
 [24 33]]


In [25]:
a=np.array([45,1,5,7]).reshape(2,2)
b=np.array([2,1,2,4]).reshape(2,2)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
print(a*b)

[[45  1]
 [ 5  7]]
-----------------------
[[2 1]
 [2 4]]
-----------------------
[[90  1]
 [10 28]]


In [ ]:
#one to one fun
a=np.array([45,1,5,7]).reshape(2,2)
b=np.array([2,1,2,4]).reshape(2,2)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
c=a.dot(b)
print(c)

[[45  1]
 [ 5  7]]
-----------------------
[[2 1]
 [2 4]]
-----------------------
[[92 49]
 [24 33]]


In [ ]:
#to acess max elemente in rows and col
a=np.array([45,1,5,7]).reshape(2,2)
print(a)
print("-----------------------")
print(a.max(axis=0))     #axis 0-column
print("-----------------------")
print(a.max(axis=1))        #axis 1-row

[[45  1]
 [ 5  7]]
-----------------------
[45  7]
-----------------------
[45  7]


In [ ]:
#to print min in rows and column
a=np.array([45,1,5,7]).reshape(2,2)
print(a)
print("-----------------------")
print(a.min(axis=0))     #axis 0-column
print("-----------------------")
print(a.min(axis=1))        #axis 1-row

[[45  1]
 [ 5  7]]
-----------------------
[5 1]
-----------------------
[1 5]


In [ ]:
#joining arrays in vertically
a=np.array([45,1,5,7,22,5]).reshape(2,3)
b=np.array([2,1,2,4,2,20]).reshape(2,3)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
print("After vertically stackin the arrays")
print(np.vstack((a,b)))

[[45  1  5]
 [ 7 22  5]]
-----------------------
[[ 2  1  2]
 [ 4  2 20]]
-----------------------
After vertically stackin the arrays
[[45  1  5]
 [ 7 22  5]
 [ 2  1  2]
 [ 4  2 20]]


In [ ]:
#joining arrays in horizontally
a=np.array([45,1,5,7]).reshape(2,2)
b=np.array([2,1,2,4]).reshape(2,2)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
print("After horizontcally stackin the arrays")
print(np.hstack((a,b)))

[[45  1]
 [ 5  7]]
-----------------------
[[2 1]
 [2 4]]
-----------------------
After horizontcally stackin the arrays
[[45  1  2  1]
 [ 5  7  2  4]]


In [26]:
a=np.array([45,1,5,7]).reshape(2,2)
b=np.array([2,1,2,4]).reshape(2,2)
print(a)
print("-----------------------")
print(b)
print("-----------------------")
print("After horizontcally stackin the arrays")
print(np.stack((a,b)))

[[45  1]
 [ 5  7]]
-----------------------
[[2 1]
 [2 4]]
-----------------------
After horizontcally stackin the arrays
[[[45  1]
  [ 5  7]]

 [[ 2  1]
  [ 2  4]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after dstark")
print(np.dstack(a))    #no.of rows-->no.of groups
#no.of col in evy group-->no.of rows in evy group
#[0,0],[1,1]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstark
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [29]:
#splitting array to equal parts
a=np.arange(18).reshape(6,3)
print(a)
print("after spliting")
print(np.vsplit(a,2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after spliting
[array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting array i vertical not equal parts
a=np.arange(18).reshape(6,3)
print(a)
print("after spliting")
print(np.vsplit(a,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after spliting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [32]:
#splitting array in horizontal not equal parts
a=np.arange(18).reshape(3,6)
print(a)
print("after spliting")
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after spliting
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [ ]:
#splitting array in horizontal not equal parts
a=np.arange(18).reshape(3,6)
print(a)
print("after spliting")
print(np.hsplit(a,(2,5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after spliting
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]]), array([[ 5],
       [11],
       [17]])]


In [ ]:
#splitting array in horizontal not equal parts
a=np.arange(18).reshape(6,3)
print(a)
print("after spliting")
print(np.hsplit(a,(1,2)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after spliting
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
#max giving index value
a=np.array([17,4,3,12,66,8,1,44,67]).reshape(3,3)
print(a)
print("after spliting")            #index
print(a.argmax())

[[17  4  3]
 [12 66  8]
 [ 1 44 67]]
after spliting
8


In [ ]:
#max giving index value axis=0
a=np.array([17,4,3,12,66,8,1,44,6]).reshape(3,3)                 #[00000
                                                                   #11111]
print(a)
print("after spliting")
print(a.argmax(axis=0))

[[17  4  3]
 [12 66  8]
 [ 1 44  6]]
after spliting
[0 1 1]


In [ ]:
#max giving index value axis=1
a=np.array([17,4,3,12,66,8,1,44,6]).reshape(3,3)                 #[0123
                                                                   #0123]
print(a)
print("after spliting")
print(a.argmax(axis=1))

[[17  4  3]
 [12 66  8]
 [ 1 44  6]]
after spliting
[0 1 1]


In [ ]:
#max giving index value
a=np.array([17,4,3,12,66,8,1,44,67]).reshape(3,3)
print(a)
print("after spliting")
print(a.argmin())

[[17  4  3]
 [12 66  8]
 [ 1 44 67]]
after spliting
6


In [ ]:
#max giving index value axis=0
a=np.array([17,4,3,12,66,8,1,44,6]).reshape(3,3)                 #[0.0.0.0.0
                                                                   #1.1.1.1.1]
print(a)
print("after spliting")
print(a.argmin(axis=0))

[[17  4  3]
 [12 66  8]
 [ 1 44  6]]
after spliting
[2 0 0]


In [ ]:
#max giving index value axis=1
a=np.array([17,4,3,12,66,8,1,44,6]).reshape(3,3)                 #[0.1.2.3
                                                                   #0.1.2.3]
print(a)
print("after spliting")
print(a.argmin(axis=1))

[[17  4  3]
 [12 66  8]
 [ 1 44  6]]
after spliting
[2 2 0]


In [ ]:
#statistics
#mean,median,std,var
a=np.array([12,34,5,6,8,5])
print("mean:",np.mean(a))
print("median:",np.median(a))
print("variance:",np.var(a))
print("std:",np.std(a))

mean: 11.666666666666666
median: 7.0
variance: 105.55555555555556
std: 10.274023338281628


In [ ]:
#trigonometry
a=np.pi                     #in radius
print(a)

3.141592653589793


In [ ]:
np.rad2deg(a)              #in degree

180.0

In [ ]:
b=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(b)

[0.78539816 1.04719755 1.57079633 3.14159265]
[ 45.  60.  90. 180.]


In [ ]:
print(np.rad2deg(b))

[ 45.  60.  90. 180.]


In [ ]:
c=np.array([0,30,45,60,90,120,180])
d=np.deg2rad(c)
print(d)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)                #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)                 #cos^-1

0.0

In [ ]:
np.arctan(1)                 #tan^-1

0.7853981633974483

In [ ]:
#hypot
a=6
b=4
print(np.hypot(a,b))          #hypoteuse

7.211102550927978


In [ ]:
#hypot
a=6
b=8
print(np.hypot(a,b))

10.0


SEARCHING

In [ ]:
a=np.array([90,2,3,1,67,1,4,9])
print(np.where(a==1))

(array([3, 5]),)


In [ ]:
a=np.array([90,2,3,1,67,1,4,9])
print(np.where(a%2==0))

(array([0, 1, 6]),)


In [ ]:
#search sorted
a=np.array([5,11,24,28,35,88])
print(np.searchsorted(a,35))           #outputs the index of a sorted element!

4


LINEAR ALGEBRA AND UFUNC

In [35]:
a=np.array([33,5,12,5,2])
b=np.array([5,11,24,35,1])
print(np.add(a,b))
print(np.divmod(a,b))
print(np.subtract(a,b))
print(np.mod(a,b))
print(np.diff(a))

[38 16 36 40  3]
(array([6, 0, 0, 0, 2]), array([ 3,  5, 12,  5,  0]))
[ 28  -6 -12 -30   1]
[ 3  5 12  5  0]
[-28   7  -7  -3]


In [ ]:
a=np.array([33,5,12,5,2])
b=np.sort(a)
print(b)

[ 2  5  5 12 33]


SET FUNCTION

In [ ]:
a=np.array([33,5,12,5,2])
b=np.array([21,4,1,6,33])
print(np.union1d(a,b))

[ 1  2  4  5  6 12 21 33]


In [37]:
print(np.intersect1d(a,b))

[5]


Rounding !

In [ ]:
#trunc
a=np.trunc([-3.1666,3.6677])
print(a)

[-3.  3.]


In [ ]:
#fix
a=np.fix([-3.1666,3.6677])
print(a)

[-3.  3.]


In [ ]:
#around
a=np.around([-3.12236],4)
print(a)
b=np.around([4.5,-4.5,6.2,6.7])
print(b)

[-3.1224]
[ 4. -4.  6.  7.]


In [ ]:
#floor
a=np.floor([-3.1666,3.6677])
print(a)

[-4.  3.]


In [ ]:
#ceil
a=np.ceil([-3.1666,3.6677])
print(a)

[-3.  4.]


More Function

In [ ]:
a=np.array([3,4,16,19,10])
print(np.cumsum(a))          #cumulative sum
print(np.cumproduct(a))

[ 3  7 23 42 52]
[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,665))

952
5


In [ ]:
a=np.array([45,65,30])           #lcm.reduce is used to find multiple numbers of lcm
print(np.lcm.reduce(a))

1170


In [ ]:
a=np.array([45,65,30])           #gcd.reduce is used to find multiple numbers of gcd
print("gcd",np.gcd.reduce(a))

gcd 5


In [ ]:
#inverse matrix
#linalg.inv contain inverse function(sub function)
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Random

In [ ]:
from numpy import random as rd

In [ ]:
a=rd.rand()   #n #default limit 0 to 0.99
print(a)

0.6022795028991419


In [ ]:
a=rd.rand(10)
print(a)

[0.95797041 0.95114658 0.37273654 0.06889051 0.91280287 0.34332283
 0.55102459 0.3628473  0.7338087  0.43788979]


In [38]:
a=rd.randint(5)  #randint(limit)-->0,1,2,3,4
print(a)

1


In [ ]:
a=rd.rand(10)
print(a)     #n 3default limit 0 to 0.99

[0.72269106 0.80572185 0.31015704 0.05647906 0.02366552 0.48129507
 0.25074552 0.39966084 0.5476052  0.67459355]


In [ ]:
a=rd.randint(50,size=6)  #(limit with size)
print(a)

[ 0 34  3 23 48 34]


In [ ]:
#inner
a=np.array([1,2,3])
b=np.array([4,5,6])
#1*4,2*5,3*6
print(np.inner(a,b))

32


In [ ]:
#outer
a=np.array([1,2,3])
b=np.array([4,5,6])
#1
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#cross
a=np.array([1,2,3])
b=np.array([3,7,8])
#
print(np.cross(a,b))

[-5  1  1]
