In [ ]:
#variable
a=10
print("iam ",a,"years old")

iam  10 years old


In [ ]:
#adding ops on int variables
a=int(input("enter a value"))
b=int(input("enter b value"))
print("sum is",a+b)
print("diff is",b-a)
print("product is",a*b)
print("quotien is",a/b)
print("remainder is",a%b)
print("power of a to be is",a**b)
print("floor",a//b)


enter a value2
enter b value4
sum is 6
diff is 2
product is 8
quotien is 0.5
remainder is 2
power of a to be is 16
floor 0


In [6]:
#get the salary from the user if the salary then or equal 50k apply 10% tax ditection if the salary is less then 50k apply 5% tax,if the salary is more then 70k apply 12% tax if your salary exceed 1L.print your promoted to next level.
a=int(input("enter salary"))
if(a<50000):
  print("salary is 5%",a-(a*(5/100)))
elif(a<=70000):
  print("salary is 10%",a-(a*(10/100)))
elif(a<100000):
  print("salary i 12%s",a-(a*(12/100)))
else:
  print("promoted next level")

enter salary100000
promoted next level


In [19]:
a=int(input("enter salary"))
if(a>=0 and a<50000):
  print("salary is 5%",a-(a*(5/100)))
elif(a>=50000 and a<70000):
  print("salary is 10%",a-(a*(10/100)))
elif(a>=70000 and a<100000):
  print("salary i 12%s",a-(a*(12/100)))
else:
  print("promoted next level")

enter salary70000
salary i 12%s 61600.0


In [20]:
a=int(input("enter salary"))
if(a%2==0):
  print("even")

enter salary58
even


In [ ]:
#range
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [21]:
n=int(input("enter n"))
for i in range(1,21):
  print(n,"x",i,"=",n*i)

enter n42
42 x 1 = 42
42 x 2 = 84
42 x 3 = 126
42 x 4 = 168
42 x 5 = 210
42 x 6 = 252
42 x 7 = 294
42 x 8 = 336
42 x 9 = 378
42 x 10 = 420
42 x 11 = 462
42 x 12 = 504
42 x 13 = 546
42 x 14 = 588
42 x 15 = 630
42 x 16 = 672
42 x 17 = 714
42 x 18 = 756
42 x 19 = 798
42 x 20 = 840


In [ ]:
#while
n=int(input("enter n"))
i=1
while(i<=20):
  print(n,"x",i,"=",n*i)
  i=i+1

enter n45
45 x 1 = 45
45 x 2 = 90
45 x 3 = 135
45 x 4 = 180
45 x 5 = 225
45 x 6 = 270
45 x 7 = 315
45 x 8 = 360
45 x 9 = 405
45 x 10 = 450
45 x 11 = 495
45 x 12 = 540
45 x 13 = 585
45 x 14 = 630
45 x 15 = 675
45 x 16 = 720
45 x 17 = 765
45 x 18 = 810
45 x 19 = 855
45 x 20 = 900


In [ ]:
#create list
l=["hi",5,33,'A',4.3]
for i in l:
  print(i)

hi
5
33
A
4.3


In [ ]:
#append
l=["hi",5,33,'S',5.3]
l.append("jyo")        #listname.append("value")
print(l)

['hi', 5, 33, 'S', 5.3, 'jyo']


In [ ]:
#insert
l=["hi",5,33,'S',5.3]
l.insert(3,"jyo")      #listname.insert(index,valu)
print(l)

['hi', 5, 33, 'jyo', 'S', 5.3]


In [ ]:
#remove
l=["hi",5,33,'S',5.3]
l.pop(3)               #listname.pap(Index)
print(l)

['hi', 5, 33, 5.3]


In [ ]:
#remove using remove
l=["hi",5,33,'S',5.3]
l.remove(5)         #listname.remove(value)
print(l)

['hi', 33, 'S', 5.3]


In [ ]:
#remove pop
l=["hi",5,33,'S',5.3]
l.pop()
print(l)

['hi', 5, 33, 'S']


In [ ]:
#remove listvalues
l=["hi",5,33,'S',5.3]
l.clear()
print(l)

[]


In [ ]:
#extend or +symboll
l2=["mutable","text"]
l3=[4,7,11,3.4]
l2=(l2+l)
l3.extend(l2)
print(l2)
print(l3)

['mutable', 'text', 'hi', 5, 33, 'S']
[4, 7, 11, 3.4, 'mutable', 'text', 'hi', 5, 33, 'S']


In [ ]:
#take the number from the user which is a salary,if the salary is more them 50000 there is 10% tax print his final salary.
a=int(input("enter salary:"))
if(a>50000):
  tax=a*(10/100)
  a=a-tax
  print(a)
else:
  print("no tax deducation your salary is:",a)

enter salary:58000
52200.0


In [ ]:
#create a list of 10 integers elementes print there squares save this squares in a new list.
l=[21,4,6,22,55,3,1,5,4,7]
l2=[]
for i in l:
  i=i*i
  l2.append(i)
print(l2)

[441, 16, 36, 484, 3025, 9, 1, 25, 16, 49]


In [ ]:
#list compresion
#newlist=[output for]
l=[4,5,33,6,5.3]
d=[i*i for i in l]
print(d)

[16, 25, 1089, 36, 28.09]


In [ ]:
#list comprehension
#newlist=[output for condition]
l=[4,5,33,6,5.3]
d=[i*i for i in l if(i%2==0)]
print(d)

[16, 36]


In [ ]:
#list comprehension
#newlist=[output for condition]
l=[4,5,33,65,5.3]
d=[i*i for i in l if(i>50)]
print(d)

[4225]


In [ ]:
#list comprehension
#newlist=[(st of if) if (con) else (st of else)]
l1=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in l1]
print(res)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take the salary from user if salary is less them 50k 10% tax,otherwise 15% tax.
sal=int(input("enter salary"))
l1=[]
l1.append(sal)
res=[i-(i*(10/100)) if i<50000 else i-(i*(15/100)) for i in l1]
print(res)

enter salary50400
[42840.0]


In [ ]:
#same as list
l=[78000,34000,14000]
res=[i-(i*(10/100)) if i<50000 else i-(i*(15/100)) for i in l]
print(res)

[66300.0, 30600.0, 12600.0]


In [ ]:
#dictionary
#dictname={key:val,key2:val}
dict1={"mentor":"jwalitha",35:"likitha",25:"ramya",75:"lavanya"}
print(dict1.keys())
print(dict1.values())
print(dict1[75])

dict_keys(['mentor', 35, 25, 75])
dict_values(['jwalitha', 'likitha', 'ramya', 'lavanya'])
lavanya


In [ ]:
#nested dictionary
dict2={"dept":"cse","details":{'year':'II','sec':'D','count':71}}
print(dict2["details"]['sec'])

D


In [ ]:
#nested dictionary
dict2={"dept":"cse","details":{'year':'II','sec':'D','count':71}}
print("year is",dict2["details"]["year"])
print("secton is",dict2["details"]["sec"])
print("strength is",dict2["details"]["count"])

year is II
secton is D
strength is 71


In [ ]:
#create keys and values using 2 lists
id=[34,55,12,35,12]
names=["joe","suchi","rohini","shankar","mani"]
nz=(zip(id,names))
for i in nz:
  print(i)

(34, 'joe')
(55, 'suchi')
(12, 'rohini')
(35, 'shankar')
(12, 'mani')


In [ ]:
#create dictionary using 2 lists
id=[34,55,12,35,12]
names=["joe","suchi","rohini","shankar","mani"]
nz=dict((zip(names,id)))
print(nz)

{'joe': 34, 'suchi': 55, 'rohini': 12, 'shankar': 35, 'mani': 12}


In [23]:
#create a 1d array
import numpy as np
a=np.array([1,2,3,4])
print(a.ndim)
print(a.shape)


1
(4,)


In [ ]:
#create a 2 dim array
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[15,66,77,88]])
#element in each row=coloumn                              #2d array
print(a.ndim)
print(a.shape)
print(a)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [15 66 77 88]]


In [ ]:
#create a 3d array
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[15,66,77,88]],[[1,2,9,8],[1,3,4,3],[5,6,5,9]]])
#element in each row=coloumn                              #3d array
print(a.ndim)
print(a.shape)
print(a)

3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [15 66 77 88]]

 [[ 1  2  9  8]
  [ 1  3  4  3]
  [ 5  6  5  9]]]


In [ ]:
#ones() function use
a=np.ones((4,2,3))              #groups,rows,col
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#zeros fun using
a=np.zeros((2,1,3))              #groups,rows,col
print(a)

[[[0. 0. 0.]]

 [[0. 0. 0.]]]


In [24]:
#identity matrix  eye fun
a=np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.arange(1,10,3)         #start,stop,step
print(a)
print(type(a))

[1 4 7]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisiable by 8 by range function between 1 to 1000
a=np.arange(8,1001,8)
print(a)
print(type(a))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
#spilting a range into n numbers with common diffrence
a=np.linspace(31,12,8)
print(a)

[31.         28.28571429 25.57142857 22.85714286 20.14285714 17.42857143
 14.71428571 12.        ]


In [ ]:
#study sets and tuple
#documentation
#QRcodw